apiVersion: apps/v1
kind: Deployment
metadata:
  name: locust-worker
  namespace: locust
  labels:
    name: locust-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: locust-worker
  template:
    metadata:
      labels:
        app: locust-worker
    spec:
      containers:
        - name: locust-worker
          imagePullPolicy: Always
          image: ndquynhz/locust:stable
          env:
            - name: ATTACKED_HOST
              valueFrom:
                configMapKeyRef:
                  name: locust-cm
                  key: ATTACKED_HOST
            - name: LOCUST_MODE
              value: WORKER 
            - name: LOCUST_MASTER
              value: locust-master
          volumeMounts:
          - mountPath: /locust
            name: locust-scripts
      volumes:
      - name: locust-scripts
        configMap:
          name: scripts-cm
