apiVersion: apps/v1
kind: Deployment
metadata:
  name: locust-master
  namespace: locust
  labels:
    name: locust-master
spec:
  replicas: 1
  selector:
    matchLabels:
      app: locust-master
  template:
    metadata:
      labels:
        app: locust-master
    spec:
      containers:
        - name: locust-master
          imagePullPolicy: Always
          image: ndquynhz/locust:stable
          env:
            - name: ATTACKED_HOST
              valueFrom:
                configMapKeyRef:
                  name: locust-cm
                  key: ATTACKED_HOST
            - name: LOCUST_MODE
              value: MASTER
          volumeMounts:
          - mountPath: /locust
            name: locust-scripts
          ports:
            - name: loc-master-web
              containerPort: 8089
              protocol: TCP
            - name: loc-master-p1
              containerPort: 5557
              protocol: TCP
            - name: loc-master-p2
              containerPort: 5558
              protocol: TCP
      volumes:
      - name: locust-scripts
        configMap:
          name: scripts-cm
