apiVersion: v1
kind: ConfigMap
metadata:
  namespace: locust
  name: scripts-cm
data:
  locustfile.py: |
    import time
    import request
    from locust import HttpUser, task
    
    proxies = {
	"http": "104.16.104.228:80"
    }
    
    class QuickstartUser(HttpUser):
        @task
        def index(self):
            self.client.get("/", proxies = proxies)
